apiVersion: apps/v1
kind: Deployment
metadata:
  name: workwave-app
  labels:
    app: workwave-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: workwave-app
  template:
    metadata:
      labels:
        app: workwave-app
    spec:
      containers:
        - name: workwave-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80